intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

# Public headers.
#
pub = [dir_path] ../include/glob/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{glob}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{glob}: {hxx cxx}{**} $impl_libs $intf_libs

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/source/
src_pfx_src = [dir_path] $src_root/source/

cxx.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
                "-I$out_pfx_inc" "-I$src_pfx_inc"

{hbmia obja}{*}: cxx.poptions += -DGLOB_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DGLOB_SHARED_BUILD

# Export options.
#
lib{glob}:
{
  cxx.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  cxx.export.libs = $intf_libs
}

liba{glob}: cxx.export.poptions += -DGLOB_STATIC
libs{glob}: cxx.export.poptions += -DGLOB_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{glob}: bin.lib.version = "-$version.project_id"
else
  lib{glob}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
hxx{*}: install = false
