intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{glob}: libul{glob}: {hxx ixx txx cxx}{** -version} hxx{version} $impl_libs $intf_libs

hxx{version}: in{version} $src_root/manifest

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DGLOB_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DGLOB_SHARED_BUILD

# Export options.
#
libs{glob}: def{glob}: include = ($cxx.target.system == 'win32-msvc')
def{glob}: libul{glob}

if ($cxx.target.system == 'mingw32')
  cxx.loptions += -Wl,--export-all-symbols

lib{glob}:
{
  cxx.export.poptions = "-I$out_root" "-I$src_root"
  cxx.export.libs = $intf_libs
}

liba{glob}: cxx.export.poptions += -DGLOB_STATIC
libs{glob}: cxx.export.poptions += -DGLOB_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{glob}: bin.lib.version = "-$version.project_id"
else
  lib{glob}: bin.lib.version = "-$version.major.$version.minor"

# Install into the glob/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/glob/
  install.subdirs = true
}
